### ISSUE TITLE
Perimeter offset and core depth

### ISSUE THREAD

**Issue by Cyubahir** [MITSustainableDesignLab/umidocs#19]
_UMI (Urban modeling interface)_

A full description of the perimeter zone and core zone's operation as well as how the shoebox model interprets it for roof or ground area calculations.
For example, in this case, a shoebox model with a length of 12 m, a width of 8.5 m, and a height of 4.5 m. What should the perimeter offset and core depth be? And, based on that, how can the roof and gross area be calculated?

Thanks!

**Comment by Cyubahir** [comment]
I have checked the documentation and I understand that the perimeter offset should be between (0-3m) and core depth also have to be chosen according to the building volume. However, I still don't understand how UMI calculate gross roof area with these parameters. 

For instance, In this scenario, the shoebox volume was (12m width, 8.5m length, 4.5m height) with perimeter offset of 3m and core depth of 6m. After simulation, the generated IDF file showed that the total gross roof area used for energy simulation is 29.45 m2 which is significantly less than the actual shoebox roof area (12m*8.5m= 102 m2). In fact, IDF file showed that this total gross roof area is derived from the sum of Perimeter zone area (25.46 m2) and Core zone area (4.36 m2). 

Therefore, my issue is figuring out how UMI calculates the perimeter and core zone areas.

Thank you for your assistance.

**Comment by Cyubahir** [comment]
Thank you.

Another issue concern infiltration, I would like to know whether UMI uses a wind-driven infiltration flow at 50 Pa or fixed infiltration.

**Comment by samuelduchesne** [comment]
I believe it is a simple fixed calculation. Again, this is something you can confirm in the IDF file if you wish so

**Comment by Cyubahir** [comment]
> All your calculations are correct.
> 
> The shoebox represents a certain floor area from a bigger building volume. Therefore, the surfaces of type "Roof" (one in the perimeter zone and one in the core zone) have an area that is the ratio of full-building roof area to shoebox roof area. The rest is considered adiabatic. A similar treatment is given to floors.
> 
> If you create a DWG from the idf file and visualize it in a 3D CAD viewer such as Rhino, you'll see that the "roof" of the shoebox is made up of 4 surfaces, 2 of which are of type "Roof" (with solar and wind incidence) and two are of type "Adiabatic" (no-sun and no-wind).

I am still confused regarding the roof surface area calculation.

According to this algorithm you explained above to calculate the surface roof area (ratio of full building area to shoebox roof area) and with that same example, I showed previously, I still couldn't figure out how these input values (core depth and the perimeter offset ) were used to calculate the shoebox roof area since the full building area was 102 m2. Thanks!

**Comment by samuelduchesne** [comment]
You could refer to this paper for more details: https://www.sciencedirect.com/science/article/abs/pii/S0378778817300932
