### ISSUE TITLE
Window U-Factor calculation by UMI

### ISSUE THREAD

**Issue by Cyubahir** [MITSustainableDesignLab/umidocs#20]
I have an issue regarding how UMI calculates the U-Factor of the window.

For instance, In this case, I had an Air-gas filled triple-pane window (4-12-4-12-4) with a glazing thermal conductivity of (0.8 W/mK), and the generated IDF file after simulation indicated a U-factor of (1.764 W/m2K) which differed from what I obtained by hand calculation using the standard formula.

Therefore, I would like to know how UMI calculates the U-Factor of the window.

**Comment by samuelduchesne** [comment]
Hi @Cyubahir, UMI does not calculate any U-Factors, EnergyPlus does. You specify the window constructions (layer by layer in the template editor) and those are translated as such in the EnergyPlus IDF model. Then EnergyPlus uses the method as described in: https://bigladdersoftware.com/epx/docs/9-4/engineering-reference/window-calculation-module.html. It is a quite an advanced method, which could explain why you have different results with a hand calculation.
