### ISSUE TITLE
umi 3.1.0 software cannot be installed

### ISSUE THREAD

**Issue by rehack** [MITSustainableDesignLab/umidocs#22]
bug:
![image](https://github.com/MITSustainableDesignLab/umidocs/assets/9047357/9bf65ad9-95d5-4022-8f7b-fad436d88035)

os: windows10

**Comment by rehack** [comment]
@samuelduchesne

**Comment by samuelduchesne** [comment]
This repository is not meant for troubleshooting UMI. Please communicate with info<at>urbanmodeling.net
